# -*- coding: utf-8 -*-
"""Automate_Mohammad Fathorrosi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BojBPbvvWVEGyaYNZXROXBbCiU3w5LdP
"""

# automate
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

def load_data(path):
    """Load dataset dari CSV."""
    df = pd.read_csv(path)
    print(f"Data berhasil dimuat dari: {path}")
    print(f"Shape: {df.shape}")
    return df

def preprocess_step1_drop_columns(df):
    """Copy dataframe dan hapus kolom yang tidak relevan."""
    df_clean = df.copy()
    if 'customerID' in df_clean.columns:
        df_clean = df_clean.drop(columns=['customerID'])
    return df_clean

def preprocess_step2_handle_totalcharges(df):
    """Konversi TotalCharges ke numerik & imputasi missing value."""
    if 'TotalCharges' in df.columns:
        df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
        imputer = SimpleImputer(strategy='median')
        df[['TotalCharges']] = imputer.fit_transform(df[['TotalCharges']])
    return df

def preprocess_step3_drop_duplicates(df):
    """Hapus baris duplikat."""
    return df.drop_duplicates()

def preprocess_step4_encode_target(df):
    """Encoding target Churn menjadi numerik."""
    if 'Churn' in df.columns:
        df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})
    return df

def preprocess_step5_encode_categorical(df):
    """One-Hot Encoding untuk kolom kategorikal."""
    cat_cols = df.select_dtypes(include='object').columns.tolist()
    return pd.get_dummies(df, columns=cat_cols, drop_first=True)

def preprocess_step6_scaling(df):
    """Standarisasi fitur numerik dengan StandardScaler."""
    num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
    num_cols = [c for c in num_cols if c in df.columns]
    scaler = StandardScaler()
    df[num_cols] = scaler.fit_transform(df[num_cols])
    return df

def preprocess_data(df):
    """Melakukan preprocessing lengkap secara berurutan."""
    df = preprocess_step1_drop_columns(df)
    df = preprocess_step2_handle_totalcharges(df)
    df = preprocess_step3_drop_duplicates(df)
    df = preprocess_step4_encode_target(df)
    df = preprocess_step5_encode_categorical(df)
    df = preprocess_step6_scaling(df)
    return df

def save_data(df, output_path):
    """Simpan dataset hasil preprocessing."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False)
    print(f"Dataset tersimpan di: {output_path}")

if __name__ == "__main__":
    RAW_PATH = 'namadataset_raw/telco_churn.csv'
    OUT_PATH = 'namadataset_preprocessing/telco_churn_preprocessing.csv'

    print("=" * 50)
    print("MULAI PREPROCESSING")
    print("=" * 50)

    print("\n[1] Loading data...")
    df = load_data(RAW_PATH)

    print("\n[2] Preprocessing...")
    df_clean = preprocess_data(df)

    print("\n[3] Saving...")
    save_data(df_clean, OUT_PATH)

    print("\n" + "=" * 50)
    print(f"SELESAI! Shape akhir: {df_clean.shape}")
    print("=" * 50)